pipeline
{
agent any
  {
    stages{
      stage("build")
      {
        steps{
      echo 'Hello'
        }
      }
      stage("test")
      {
        steps{
        echo 'Test'
        }
      }
    }



    
  }
}
